#!/usr/bin/env python3
"""
Compiles and deterministically splits the hash-locked Hermes Agent dependency closure.

Usage:
    python3 scripts/compile-hermes-requirements.py          # Regenerate and split requirements
    python3 scripts/compile-hermes-requirements.py --check  # Verify committed files match (drift check)
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

MAX_CHUNK_LINES = 225
MAX_CHUNK_BYTES = 18000

REPO_ROOT = Path(__file__).resolve().parent.parent
HERMES_DIR = REPO_ROOT / "docker" / "hermes"
REQ_IN = HERMES_DIR / "requirements.in"
REQ_TXT = HERMES_DIR / "requirements.txt"


def find_uv() -> str:
    uv_bin = shutil.which("uv")
    if uv_bin:
        return uv_bin
    local_uv = Path.home() / ".local" / "bin" / "uv"
    if local_uv.exists() and os.access(local_uv, os.X_OK):
        return str(local_uv)
    raise RuntimeError(
        "uv executable not found. Install uv to regenerate requirements: https://github.com/astral-sh/uv"
    )


def compile_closure() -> str:
    uv_bin = find_uv()
    cmd = [
        uv_bin,
        "pip",
        "compile",
        str(REQ_IN),
        "--python-version",
        "3.13",
        "--python-platform",
        "linux",
        "--generate-hashes",
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return res.stdout


def parse_package_blocks(raw_output: str) -> list[str]:
    blocks: list[str] = []
    current: list[str] = []
    for line in raw_output.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("# This file was autogenerated") or stripped.startswith(
            "#    uv pip compile"
        ):
            continue
        if stripped and not stripped.startswith("#") and not stripped.startswith("--hash"):
            if current:
                blocks.append("".join(current))
                current = []
        if current or (stripped and not stripped.startswith("#")):
            current.append(line)
    if current:
        blocks.append("".join(current))
    return blocks


def chunk_blocks(blocks: list[str]) -> list[list[str]]:
    chunks: list[list[str]] = []
    curr_chunk: list[str] = []
    curr_lines = 0
    curr_bytes = 0

    for block in blocks:
        b_lines = block.count("\n")
        b_bytes = len(block.encode("utf-8"))
        if curr_chunk and (
            curr_lines + b_lines > MAX_CHUNK_LINES
            or curr_bytes + b_bytes > MAX_CHUNK_BYTES
        ):
            chunks.append(curr_chunk)
            curr_chunk = []
            curr_lines = 0
            curr_bytes = 0
        curr_chunk.append(block)
        curr_lines += b_lines
        curr_bytes += b_bytes

    if curr_chunk:
        chunks.append(curr_chunk)
    return chunks


def build_generated_files(chunks: list[list[str]]) -> dict[str, str]:
    files: dict[str, str] = {}
    top_level_lines = [
        "# Autogenerated top-level Hermes requirements index.\n",
        "# Resolves the full hash-locked dependency closure via chunk includes.\n",
        "# Each include file is sized <250 lines and <20KB for code review integrity.\n",
        "# Regenerate with: python3 scripts/compile-hermes-requirements.py\n",
    ]

    for idx, chunk in enumerate(chunks, 1):
        filename = f"requirements-{idx:02d}.txt"
        top_level_lines.append(f"-r {filename}\n")
        chunk_content = (
            f"# Autogenerated chunk {idx:02d} by scripts/compile-hermes-requirements.py. Do not edit directly.\n"
            + "".join(chunk)
        )
        files[filename] = chunk_content

    files["requirements.txt"] = "".join(top_level_lines)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check for drift without writing")
    args = parser.parse_args()

    raw_closure = compile_closure()
    blocks = parse_package_blocks(raw_closure)
    chunks = chunk_blocks(blocks)
    generated = build_generated_files(chunks)

    if args.check:
        # Check top-level requirements.txt
        if not REQ_TXT.exists():
            print(f"ERROR: {REQ_TXT} does not exist", file=sys.stderr)
            return 1
        current_req = REQ_TXT.read_text("utf-8")
        if current_req != generated["requirements.txt"]:
            print(f"ERROR: {REQ_TXT} differs from generated output", file=sys.stderr)
            return 1

        # Check each chunk file
        for filename, expected_content in generated.items():
            if filename == "requirements.txt":
                continue
            chunk_path = HERMES_DIR / filename
            if not chunk_path.exists():
                print(f"ERROR: {chunk_path} does not exist", file=sys.stderr)
                return 1
            current_content = chunk_path.read_text("utf-8")
            if current_content != expected_content:
                print(f"ERROR: {chunk_path} differs from generated output", file=sys.stderr)
                return 1

        # Ensure no extraneous chunk files exist
        existing_chunks = sorted(HERMES_DIR.glob("requirements-*.txt"))
        expected_names = set(generated.keys()) - {"requirements.txt"}
        for chunk in existing_chunks:
            if chunk.name not in expected_names:
                print(f"ERROR: Unexpected extra chunk file: {chunk.name}", file=sys.stderr)
                return 1

        print("OK: Hermes requirements hash lock closure and chunks match exactly (no drift).")
        return 0

    # Write files
    for chunk_file in HERMES_DIR.glob("requirements-*.txt"):
        chunk_file.unlink()

    for filename, content in generated.items():
        out_path = HERMES_DIR / filename
        out_path.write_text(content, encoding="utf-8")
        lines = content.count("\n")
        bytes_count = len(content.encode("utf-8"))
        print(f"Wrote {filename}: {lines} lines, {bytes_count} bytes")

    print(f"Successfully compiled and split {len(blocks)} packages into {len(chunks)} chunks.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
