#!/usr/bin/env python3
"""
Compiles and deterministically splits the hash-locked Hermes Agent dependency closure.

Usage:
    python3 scripts/compile-hermes-requirements.py --check    # Verify committed files offline (drift check, no uv/network needed)
    python3 scripts/compile-hermes-requirements.py --refresh  # Explicit opt-in regeneration using pinned uv (maintainers only)
"""

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# Pinned exact uv version used for reproducible dependency compilation.
# Maintainers run --refresh intentionally when updating dependencies.
PINNED_UV_VERSION = "0.11.28"

# Reviewability thresholds: ensure every chunk is well below PR omission limits (<250 lines, <20KB)
MAX_CHUNK_LINES = 225
MAX_CHUNK_BYTES = 18000
HARD_MAX_CHUNK_LINES = 250
HARD_MAX_CHUNK_BYTES = 20480

REPO_ROOT = Path(__file__).resolve().parent.parent
HERMES_DIR = REPO_ROOT / "docker" / "hermes"
REQ_IN = HERMES_DIR / "requirements.in"
REQ_TXT = HERMES_DIR / "requirements.txt"
REQ_DIGEST = HERMES_DIR / "requirements.digest"


def find_uv_runner() -> list[str]:
    """Finds uvx or uv to execute the pinned uv tool version. Only invoked on --refresh."""
    uvx_bin = shutil.which("uvx")
    if not uvx_bin:
        local_uvx = Path.home() / ".local" / "bin" / "uvx"
        if local_uvx.exists() and os.access(local_uvx, os.X_OK):
            uvx_bin = str(local_uvx)
    if uvx_bin:
        return [uvx_bin, "--from", f"uv=={PINNED_UV_VERSION}", "uv"]

    uv_bin = shutil.which("uv")
    if not uv_bin:
        local_uv = Path.home() / ".local" / "bin" / "uv"
        if local_uv.exists() and os.access(local_uv, os.X_OK):
            uv_bin = str(local_uv)
    if uv_bin:
        return [uv_bin, "tool", "run", "--from", f"uv=={PINNED_UV_VERSION}", "uv"]

    raise RuntimeError(
        f"Neither 'uvx' nor 'uv' executable was found. Maintainers must install uv to run --refresh: "
        "https://github.com/astral-sh/uv"
    )


def compile_closure() -> str:
    """Invokes pinned uv to resolve and compile the dependency closure with hashes."""
    runner = find_uv_runner()
    cmd = runner + [
        "pip",
        "compile",
        str(REQ_IN),
        "--python-version",
        "3.13",
        "--python-platform",
        "linux",
        "--generate-hashes",
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        # Redact any userinfo in URLs from stderr: https://user:pass@host -> https://[redacted]@host
        redacted_stderr = re.sub(r"://[^/@]+@", "://[redacted]@", res.stderr)
        raise RuntimeError(
            f"uv pip compile failed (exit code {res.returncode}):\n{redacted_stderr}"
        )
    return res.stdout


def compute_normalized_closure_digest(blocks: list[str]) -> str:
    """Computes deterministic SHA-256 digest of normalized (name==version, sorted hashes) closure."""
    parsed_pkgs: dict[str, tuple[str, list[str]]] = {}
    for block in blocks:
        lines = [l.strip() for l in block.splitlines() if l.strip()]
        if not lines:
            continue
        header = lines[0].rstrip("\\").strip()
        m = re.match(r"^([a-zA-Z0-9_.-]+)==([a-zA-Z0-9_.-]+)$", header)
        if not m:
            continue
        pkg_norm = normalize_name(m.group(1))
        version = m.group(2)
        hashes: list[str] = []
        for hline in lines[1:]:
            clean_h = hline.rstrip("\\").strip()
            if clean_h.startswith("--hash="):
                hashes.append(clean_h)
        parsed_pkgs[pkg_norm] = (version, sorted(hashes))

    canonical_lines = []
    for pkg in sorted(parsed_pkgs.keys()):
        ver, hashes = parsed_pkgs[pkg]
        canonical_lines.append(f"{pkg}=={ver}")
        for h in hashes:
            canonical_lines.append(f"    {h}")
    canonical_text = "\n".join(canonical_lines) + "\n"
    return hashlib.sha256(canonical_text.encode("utf-8")).hexdigest()


def parse_package_blocks(raw_output: str) -> list[str]:
    """Parses individual package blocks from raw compile output or chunk content."""
    blocks: list[str] = []
    current: list[str] = []
    for line in raw_output.splitlines(keepends=True):
        stripped = line.strip()
        if (
            stripped.startswith("# This file was autogenerated")
            or stripped.startswith("#    uv pip compile")
            or stripped.startswith("# Autogenerated chunk")
        ):
            continue
        if stripped and not stripped.startswith("#") and not stripped.startswith("--hash"):
            if current:
                blocks.append("".join(current))
                current = []
        if current or (stripped and not stripped.startswith("#")):
            current.append(line)
    if current:
        blocks.append("".join(current))
    return blocks


def chunk_blocks(blocks: list[str]) -> list[list[str]]:
    """Greedily and deterministically partitions package blocks into reviewable chunks."""
    chunks: list[list[str]] = []
    curr_chunk: list[str] = []
    curr_lines = 0
    curr_bytes = 0

    for block in blocks:
        b_lines = block.count("\n")
        b_bytes = len(block.encode("utf-8"))
        if curr_chunk and (
            curr_lines + b_lines > MAX_CHUNK_LINES
            or curr_bytes + b_bytes > MAX_CHUNK_BYTES
        ):
            chunks.append(curr_chunk)
            curr_chunk = []
            curr_lines = 0
            curr_bytes = 0
        curr_chunk.append(block)
        curr_lines += b_lines
        curr_bytes += b_bytes

    if curr_chunk:
        chunks.append(curr_chunk)
    return chunks


def build_generated_files(chunks: list[list[str]]) -> dict[str, str]:
    """Builds index and chunk file string mappings."""
    files: dict[str, str] = {}
    top_level_lines = [
        "# Autogenerated top-level Hermes requirements index.\n",
        "# Resolves the full hash-locked dependency closure via chunk includes.\n",
        "# Each include file is sized <250 lines and <20KB for code review integrity.\n",
        "# Regenerate with: python3 scripts/compile-hermes-requirements.py --refresh\n",
    ]

    for idx, chunk in enumerate(chunks, 1):
        filename = f"requirements-{idx:02d}.txt"
        top_level_lines.append(f"-r {filename}\n")
        chunk_content = (
            f"# Autogenerated chunk {idx:02d} by scripts/compile-hermes-requirements.py. Do not edit directly.\n"
            + "".join(chunk)
        )
        files[filename] = chunk_content

    files["requirements.txt"] = "".join(top_level_lines)
    return files


def normalize_name(name: str) -> str:
    """Normalizes package name per PEP 503."""
    return re.sub(r"[-_.]+", "-", name).lower()


def validate_committed_closure() -> None:
    """
    Offline deterministic validator. Does NOT invoke uv, resolve indexes, or access network.
    Validates:
      1. requirements.in top-level pins are defined with exact '==' pins.
      2. requirements.txt exists, contains only header comments and sorted sequential '-r requirements-XX.txt' lines.
      3. All referenced chunk files exist, and no unreferenced chunk files exist on disk.
      4. Chunk size invariants: each chunk is <250 lines and <20KB.
      5. Exact pins and structure: every package entry in chunks uses exact '==' pinning and valid sha256 hashes.
      6. No duplicates: no package is declared more than once across chunks.
      7. Canonical sort order: package entries across chunks are sorted in alphabetical order.
      8. Requirements.in representation: every top-level package and version is present in the closure.
      9. Reconstructed canonical content invariants: reconstructing blocks across chunks and re-chunking
         matches the committed chunk files byte-for-byte.
     10. Multi-architecture hashes: cffi block carries wheel hashes for multiple linux architectures.
     11. Normalized closure digest: matches committed requirements.digest if present.
    """
    # 1. requirements.in
    if not REQ_IN.exists():
        raise ValueError(f"requirements.in not found at {REQ_IN}")

    req_in_content = REQ_IN.read_text(encoding="utf-8")
    top_level_pins: dict[str, dict] = {}
    for line in req_in_content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([a-zA-Z0-9_.-]+)(?:\[([a-zA-Z0-9_.,-]+)\])?==([a-zA-Z0-9_.-]+)$", line)
        if not m:
            raise ValueError(f"requirements.in entry must be an exact '==' pin: '{line}'")
        pkg_name = normalize_name(m.group(1))
        extras = [normalize_name(e.strip()) for e in m.group(2).split(",")] if m.group(2) else []
        version = m.group(3)
        top_level_pins[pkg_name] = {"version": version, "extras": extras, "raw": line}

    # 2. requirements.txt index
    if not REQ_TXT.exists():
        raise ValueError(f"requirements.txt not found at {REQ_TXT}")

    req_txt_content = REQ_TXT.read_text(encoding="utf-8")
    req_txt_lines = req_txt_content.splitlines()

    if not req_txt_lines or not req_txt_lines[0].startswith("# Autogenerated top-level Hermes requirements index."):
        raise ValueError(f"{REQ_TXT} missing expected autogenerated header")

    included_chunks: list[str] = []
    for line in req_txt_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = re.match(r"^-r\s+(requirements-\d{2}\.txt)$", stripped)
        if not m:
            raise ValueError(
                f"{REQ_TXT} contains invalid line (must be '-r requirements-XX.txt' or comment): '{stripped}'"
            )
        included_chunks.append(m.group(1))

    if not included_chunks:
        raise ValueError(f"{REQ_TXT} does not include any chunk files")

    expected_includes = [f"requirements-{idx:02d}.txt" for idx in range(1, len(included_chunks) + 1)]
    if included_chunks != expected_includes:
        raise ValueError(
            f"{REQ_TXT} includes are not strictly sequential and sorted.\n"
            f"Expected: {expected_includes}\n"
            f"Found:    {included_chunks}"
        )

    # 3. Chunk files on disk vs requirements.txt
    disk_chunks = sorted(p.name for p in HERMES_DIR.glob("requirements-*.txt"))
    if disk_chunks != included_chunks:
        missing_on_disk = set(included_chunks) - set(disk_chunks)
        unreferenced_on_disk = set(disk_chunks) - set(included_chunks)
        msg_parts = []
        if missing_on_disk:
            msg_parts.append(f"Referenced in {REQ_TXT.name} but missing on disk: {sorted(missing_on_disk)}")
        if unreferenced_on_disk:
            msg_parts.append(f"Present on disk but unreferenced in {REQ_TXT.name}: {sorted(unreferenced_on_disk)}")
        raise ValueError("Chunk file mismatch: " + "; ".join(msg_parts))

    # 4 & 5. Chunk inspection and package block validation
    all_blocks: list[str] = []
    seen_packages: dict[str, tuple[str, str]] = {}  # norm_name -> (version, chunk_name)
    ordered_package_names: list[str] = []

    for idx, chunk_name in enumerate(included_chunks, 1):
        chunk_path = HERMES_DIR / chunk_name
        chunk_content = chunk_path.read_text(encoding="utf-8")
        chunk_lines = chunk_content.splitlines(keepends=True)
        chunk_bytes = len(chunk_content.encode("utf-8"))

        if len(chunk_lines) >= HARD_MAX_CHUNK_LINES:
            raise ValueError(
                f"{chunk_name} exceeds line limit: {len(chunk_lines)} lines >= {HARD_MAX_CHUNK_LINES}"
            )
        if chunk_bytes >= HARD_MAX_CHUNK_BYTES:
            raise ValueError(
                f"{chunk_name} exceeds byte limit: {chunk_bytes} bytes >= {HARD_MAX_CHUNK_BYTES}"
            )

        expected_chunk_header = (
            f"# Autogenerated chunk {idx:02d} by scripts/compile-hermes-requirements.py. Do not edit directly."
        )
        if not chunk_lines or chunk_lines[0].strip() != expected_chunk_header:
            raise ValueError(
                f"{chunk_name} does not start with expected header:\n  Expected: {expected_chunk_header}\n  Found:    {chunk_lines[0].strip() if chunk_lines else '<empty>'}"
            )

        parsed_blocks = parse_package_blocks(chunk_content)
        if not parsed_blocks:
            raise ValueError(f"{chunk_name} contains no package blocks")

        for block in parsed_blocks:
            all_blocks.append(block)
            block_lines = [l.strip() for l in block.splitlines() if l.strip()]
            header_line = block_lines[0]
            clean_header = header_line.rstrip("\\").strip()

            pkg_match = re.match(r"^([a-zA-Z0-9_.-]+)==([a-zA-Z0-9_.-]+)$", clean_header)
            if not pkg_match:
                raise ValueError(
                    f"Package in {chunk_name} is not an exact '==' pin: '{header_line}'"
                )

            pkg_name_raw, pkg_version = pkg_match.group(1), pkg_match.group(2)
            norm_name = normalize_name(pkg_name_raw)

            if norm_name in seen_packages:
                prev_version, prev_chunk = seen_packages[norm_name]
                raise ValueError(
                    f"Duplicate package '{norm_name}' found in {chunk_name} (previously declared in {prev_chunk} as {prev_version})"
                )
            seen_packages[norm_name] = (pkg_version, chunk_name)
            ordered_package_names.append(norm_name)

            hash_lines = [l for l in block_lines[1:] if l.startswith("--hash=")]
            if not hash_lines:
                raise ValueError(
                    f"Package '{pkg_name_raw}=={pkg_version}' in {chunk_name} has no sha256 distribution hashes"
                )
            for hline in block_lines[1:]:
                clean_hline = hline.rstrip("\\").strip()
                if clean_hline.startswith("#"):
                    continue
                if not re.match(r"^--hash=sha256:[a-f0-9]{64}$", clean_hline):
                    raise ValueError(
                        f"Unexpected or malformed line in {chunk_name} for package '{pkg_name_raw}': '{hline}'"
                    )

    # 6. Alphabetical ordering invariant
    if ordered_package_names != sorted(ordered_package_names):
        for i in range(len(ordered_package_names) - 1):
            if ordered_package_names[i] > ordered_package_names[i + 1]:
                raise ValueError(
                    f"Package order in chunks is not canonically sorted: "
                    f"'{ordered_package_names[i]}' precedes '{ordered_package_names[i + 1]}'"
                )

    # 7. requirements.in representation (extras are resolver features, not standalone packages)
    for req_name, req_info in top_level_pins.items():
        if req_name not in seen_packages:
            raise ValueError(
                f"Top-level requirement '{req_info['raw']}' from requirements.in is not represented in closure chunks"
            )
        closed_version, closed_chunk = seen_packages[req_name]
        if closed_version != req_info["version"]:
            raise ValueError(
                f"Version mismatch for top-level requirement '{req_name}': "
                f"requirements.in specifies {req_info['version']}, but closure in {closed_chunk} has {closed_version}"
            )

    # 8. Reconstructed canonical content invariants:
    # Re-chunking all parsed package blocks using canonical greedy chunking must match disk chunks exactly.
    rechunked = chunk_blocks(all_blocks)
    if len(rechunked) != len(included_chunks):
        raise ValueError(
            f"Reconstructed chunk count mismatch: re-chunking produced {len(rechunked)} chunks, "
            f"but disk has {len(included_chunks)} chunks"
        )

    for idx, (expected_chunk_blocks, chunk_name) in enumerate(zip(rechunked, included_chunks), 1):
        expected_content = (
            f"# Autogenerated chunk {idx:02d} by scripts/compile-hermes-requirements.py. Do not edit directly.\n"
            + "".join(expected_chunk_blocks)
        )
        actual_content = (HERMES_DIR / chunk_name).read_text(encoding="utf-8")
        if actual_content != expected_content:
            raise ValueError(
                f"Canonical content invariant violated: {chunk_name} differs from reconstructed canonical output"
            )

    # Multi-architecture hashes check scoped to cffi block only
    cffi_block = next((b for b in all_blocks if re.match(r"^cffi==[a-zA-Z0-9_.-]+", b.strip())), None)
    if cffi_block:
        cffi_hashes = re.findall(r"--hash=sha256:[a-f0-9]{64}", cffi_block)
        if len(cffi_hashes) < 5:
            raise ValueError(
                f"Expected multi-architecture wheel hashes for cffi block, found only {len(cffi_hashes)}"
            )

    # 9. Normalized closure digest check (offline equivalence verification)
    computed_digest = compute_normalized_closure_digest(all_blocks)
    if REQ_DIGEST.exists():
        expected_digest = REQ_DIGEST.read_text(encoding="utf-8").strip()
        if computed_digest != expected_digest:
            raise ValueError(
                f"Normalized closure digest mismatch against {REQ_DIGEST.name}:\n"
                f"  Expected: {expected_digest}\n"
                f"  Computed: {computed_digest}"
            )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--check",
        action="store_true",
        help="Offline deterministic drift and integrity verification of committed requirements (no uv or network required)",
    )
    group.add_argument(
        "--refresh",
        action="store_true",
        help=f"Opt-in regeneration of requirements closure from requirements.in using pinned uv ({PINNED_UV_VERSION})",
    )
    args = parser.parse_args()

    if args.check:
        try:
            validate_committed_closure()
            print("OK: Hermes requirements hash lock closure and chunks match exactly (no drift, fully offline).")
            return 0
        except Exception as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 1

    if args.refresh:
        print(f"Resolving dependencies with pinned uv=={PINNED_UV_VERSION}...")
        raw_closure = compile_closure()
        blocks = parse_package_blocks(raw_closure)
        chunks = chunk_blocks(blocks)
        generated = build_generated_files(chunks)

        # Clear existing chunk files
        for chunk_file in HERMES_DIR.glob("requirements-*.txt"):
            chunk_file.unlink()

        # Write generated chunk files and index
        for filename, content in generated.items():
            out_path = HERMES_DIR / filename
            out_path.write_text(content, encoding="utf-8")
            lines = content.count("\n")
            bytes_count = len(content.encode("utf-8"))
            print(f"Wrote {filename}: {lines} lines, {bytes_count} bytes")

        # Write deterministic normalized closure digest
        digest = compute_normalized_closure_digest(blocks)
        REQ_DIGEST.write_text(f"{digest}\n", encoding="utf-8")
        print(f"Wrote {REQ_DIGEST.name}: {digest}")

        # Validate newly written files against all invariants
        validate_committed_closure()
        print(
            f"Successfully compiled and split {len(blocks)} packages into {len(chunks)} chunks "
            f"using uv=={PINNED_UV_VERSION}."
        )
        return 0

    return 2


if __name__ == "__main__":
    sys.exit(main())
